
#!/bin/bash
# This file is auto-generated by the GraphyFlow backend.
source /home/feiyang/set_env.sh
export XCL_EMULATION_MODE=sw_emu
DATASET="./graph.txt"
./graphyflow_host ./xclbin/graphyflow.sw_emu.xclbin $DATASET
