#ifndef __HOST_CONFIG_H__
#define __HOST_CONFIG_H__

#include <stdint.h>

#define BIG_KERNEL_NUM %BIG_KERNEL_NUM%
#define LITTLE_KERNEL_NUM %LITTLE_KERNEL_NUM%

#define NUM_KERNEL (BIG_KERNEL_NUM + LITTLE_KERNEL_NUM)

#define LITTLE_KERNEL_HBM_EDGE_ID %LITTLE_KERNEL_HBM_EDGE_ID%
#define LITTLE_KERNEL_HBM_NODE_ID %LITTLE_KERNEL_HBM_NODE_ID%
#define BIG_KERNEL_HBM_EDGE_ID %BIG_KERNEL_HBM_EDGE_ID%
#define BIG_KERNEL_HBM_NODE_ID %BIG_KERNEL_HBM_NODE_ID%

#endif /* __HOST_CONFIG_H__ */
