#!/bin/bash
# This file is auto-generated by the GraphyFlow backend.

# --- *** 关键修正：使其能够处理不同的目标 *** ---
TARGET=$1
EXECUTABLE="graphyflow_host"
XCLBIN_NAME="graphyflow_kernels"

# 默认目标为 sw_emu
if [ -z "$TARGET" ]; then
    TARGET="sw_emu"
fi

echo "--- Running for target: $TARGET ---"

# 1. 设置环境变量
source /home/feiyang/set_env.sh

if [ "$TARGET" = "sw_emu" ] || [ "$TARGET" = "hw_emu" ]; then
    export XCL_EMULATION_MODE=$TARGET
    echo "XCL_EMULATION_MODE set to: $XCL_EMULATION_MODE"
else
    # 对于 'hw'，取消设置 XCL_EMULATION_MODE
    unset XCL_EMULATION_MODE
    echo "Running on hardware, XCL_EMULATION_MODE is unset."
fi

# Optional: runtime trace config via XRT.
# Tracing is OFF by default (faster `hw_emu` runs, avoids shutdown crashes).
#
# For cycle counting, enable the trace config shipped with the project:
#   GRAPHYFLOW_TRACE=1 ./run.sh hw_emu
# or override explicitly:
#   XRT_INI_PATH=./xrt_trace.ini ./run.sh hw_emu
if [ -z "${XRT_INI_PATH:-}" ] && [ "${GRAPHYFLOW_TRACE:-0}" = "1" ] && [ -f "./xrt_trace.ini" ]; then
    export XRT_INI_PATH="./xrt_trace.ini"
fi

# 确保 LD_PRELOAD 仍然生效
if [ -z "${LD_PRELOAD:-}" ]; then
    export LD_PRELOAD=/lib/x86_64-linux-gnu/libOpenCL.so.1
fi

# 2. 动态构建 .xclbin 文件路径
XCLBIN_FILE="./xclbin/${XCLBIN_NAME}.${TARGET}.xclbin"
if [ ! -f "$XCLBIN_FILE" ]; then
    echo "Error: XCLBIN file not found at '$XCLBIN_FILE'"
    echo "Please make sure the project is built for the target '$TARGET' by running 'make all TARGET=$TARGET'"
    exit 1
fi

# 3. 运行 host 程序
DATASET="./graph.txt"
# DATASET="./rmat-19-32.txt"
./${EXECUTABLE} ${XCLBIN_FILE} $DATASET
